version: '3'
services:
  generator:
    build: .
    environment:
      FORMAT: "${FORMAT}"
      CONFIG: "${CONFIG}"
      SOURCE: "${SOURCE}"
    volumes:
      - ./output:/usr/src/typeschema/output
