version: '3'
services:
  generator:
    build: .
    environment:
      FORMAT: "${FORMAT}"
      NAMESPACE: "${NAMESPACE}"
      SOURCE: "${SOURCE}"
    volumes:
      - ./output:/usr/src/typeschema/output
