version: '3'
services:
  generator:
    build: .
    environment:
      FORMAT: "${FORMAT}"
      NAMESPACE: "${NAMESPACE}"
      SCHEMA_FILE: "output/typeschema.json"
    volumes:
      - ./output:/usr/src/typeschema/output
