name: Integration
on:
  - pull_request
  - push
jobs:
  csharp:
    name: CSharp
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: integration/csharp
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: Generate
        env:
          FORMAT: csharp
          NAMESPACE: Generator
        run: cd ../../ && docker-compose up
      - name: Move
        run: mv ../../output/*.cs .
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Run
        run: bin/Release/net6.0/generator
  go:
    name: Go
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: integration/go
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Generate
        env:
          FORMAT: go
          NAMESPACE: main
        run: cd ../../ && docker-compose up
      - name: Move
        run: mv ../../output/*.go .
      - name: Build
        run: go build -v
      - name: Test
        run: go test -v
      - name: Run
        run: ./generator
  java:
    name: Java
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: integration/java
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Generate
        env:
          FORMAT: java
          NAMESPACE: org.typeschema.generator
        run: cd ../../ && docker-compose up
      - name: Move
        run: mv ../../output/*.java .
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Run
        run: java -jar target/generator-0.1.0.jar
  php:
    name: PHP
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: integration/php
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none
      - name: Generate
        env:
          FORMAT: php
          NAMESPACE: Generator
        run: cd ../../ && docker-compose up
      - name: Move
        run: mv ../../output/*.php .
      - name: Composer install
        run: composer install --no-interaction --no-ansi --no-progress
      - name: Run
        run: php main.php
